#!/usr/bin/env bash
accent="$1"
background="$2"
foreground="$3"
zatconf=$HOME/.config/zathura
zatrc=$zatconf/zathurarc
cat "$zatconf/zathurarc.bak" > "$zatrc"
mapfile -t zat < <(grep -owE "#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})" "$zatrc")
mapfile -t zatcur < <(printf "%s\n" "${zat[@]}" | sort -us)
zataccent=${zatcur[0]}
zatbackground=${zatcur[1]}
zatforeground=${zatcur[2]}
sed -i "" -e "s/$zataccent/$accent/g" \
    -i "" -e "s/$zatbackground/$background/g" \
    -i "" -e "s/$zatforeground/$foreground/g" "$zatrc" \
