#!/usr/bin/env sh
#--------------------- Generate wallpaper 
convert $scriptdir/.themer/.bsd.png -fuzz 20% -trim +repage -fill $accent -opaque "#333333" $scriptdir/.themer/.bsd-icon.png
convert -size 2560x1080 canvas:$background -gravity center $scriptdir/.themer/.bsd-icon.png -composite $scriptdir/.themer/.background.png
#--------------------- Set newly generated wallpaper 
feh --bg-fill $scriptdir/.themer/.background.png
#---------------------
