#!/usr/bin/env bash
#--------------------- Variables.
zatconf=$HOME/.config/zathura
zatrc=$zatconf/zathurarc
#--------------------- Annoying hack, prevents colors clashing.
cat "$zatconf/zathurarc.bak" > "$zatrc"
#--------------------- Get current colors from zathura.
mapfile -t zat < <(grep -owE "#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})" "$zatrc")
mapfile -t zatcur < <(printf "%s\n" "${zat[@]}" | sort -us)
zataccent=${zatcur[0]}
zatbackground=${zatcur[1]}
zatforeground=${zatcur[2]}
#--------------------- Replace original colors with new ones.
sed -i "" -e "s/$zataccent/$accent/g" \
    -i "" -e "s/$zatbackground/$background/g" \
    -i "" -e "s/$zatforeground/$foreground/g" "$zatrc" \
#---------------------
