#!/bin/sh

# shellcheck source=/dev/null
. "$HOME/.config/gitlab"

readonly PROJECT=$(
	for project in $(find "${GITLABDIR}" -type d -depth 1 | sed -e "s|${GITLABDIR}/||g"); do
		echo "${project}"
	done | dmenu -i -p "open gitlab (${GITLABUSER}) project:"
)

readonly PROJECTPATH="${GITLABDIR}/${PROJECT}"
if [ -z "${PROJECT}" ] || [ ! -d "${PROJECTPATH}" ]; then
	exit 1
fi

${EDITOR} "${PROJECTPATH}" &
