#!/bin/sh

usage() {
	echo "usage: gl-port-update [-p port] [-c category] [-d port-dir]"
	exit 1
}

if [ $# -lt 1 ]; then
	usage
fi

PREFIX=/usr/local
SVN=${PREFIX}/bin/svn
XARGS=/usr/bin/xargs
XQ=${PREFIX}/bin/xq

PORT=
CATEGORY=
DIR=/usr/home/${USER}/Development/gitlab/${USER}/ports

while getopts "p:c:r:d:" OPT; do
	case "${OPT}" in
		p)
			PORT=${OPTARG}
			;;
		c)
			CATEGORY=${OPTARG}
			;;
		d)
			DIR=${OPTARG}
			;;
		\?)
			usage
			;;
	esac
done

if [ ! -d "${DIR}" ]; then
	echo "'${DIR}' is not a valid directory"
	exit 1
fi

if [ ! -d "${DIR}/${CATEGORY}/${PORT}" ]; then
	echo "'${CATEGORY}/${PORT}' is not a valid port"
	exit 1
fi

TMP=`mktemp -d`
(
	cd "${TMP}"
	${SVN} checkout --depth empty "https://svn.FreeBSD.org/ports/head/${CATEGORY}/${PORT}" "${TMP}" 1>/dev/null
	${SVN} log -l2 --xml | ${XQ} -r '.[].logentry[1]."@revision"' | ${XARGS} -I % svn diff -r %:HEAD > "${TMP}/${PORT}.diff"
)

PORTPATH="${DIR}/${CATEGORY}/${PORT}"
(
	cd "${PORTPATH}"
	patch -s -p0 < "${TMP}/${PORT}.diff"
	rm -rf *.orig
)

REVISION=`cd ${TMP} && ${SVN} log -l1 --xml | ${XQ} -r '.log.logentry."@revision"'`
VERSION=`awk '/(DIST|PORT)VERSION=.*/{print $2}' "${PORTPATH}/Makefile"`
SIGNED_BY=`cat /usr/home/${USER}/.gitmessage`
MESSAGE=`cat <<EOF
${CATEGORY}/${PORT}: Update to ${VERSION} https://svnweb.freebsd.org/ports?view=revision&revision=${REVISION}
${SIGNED_BY}
EOF`

(
	cd "${PORTPATH}"
	git add .
	git commit -S -m "${MESSAGE}"
)

rm -rf "${TMP}"
