#!/bin/sh

# shellcheck source=/dev/null
. "/usr/home/${USER}/.config/gitlab"

if [ ! -d "${GITLABIR}" ]; then
	mkdir -p ${GITLABDIR}
fi

for project in $(fetch -qo - "${GITLABPROJECTS}" | jq -r '.[].path'); do
	cd "${GITLABDIR}"
	if [ ! -d "${project}" ]; then
		git clone "${GITLABREPO}/${project}" > /dev/null 2>&1
	else
		cd "${project}" || exit
		git pull > /dev/null 2>&1
	fi
done
