#!/bin/sh

# shellcheck source=/dev/null
. "/usr/home/${USER}/.config/gitlab"

readonly PREFIX=/usr/local
readonly JQ=${PREFIX}/bin/jq
readonly GIT=${PREFIX}/bin/git

readonly FETCH=/usr/bin/fetch
readonly MKDIR=/bin/mkdir

set -x

if [ ! -d "${GITLABIR}" ]; then
	${MKDIR} -p ${GITLABDIR}
fi

for project in $(${FETCH} -qo - "${GITLABPROJECTS}" | ${JQ} -r '.[].path'); do
	cd "${GITLABDIR}"
	if [ ! -d "${project}" ]; then
		${GIT} clone "${GITLABREPO}/${project}" >/dev/null 2>&1
	else
		cd "${project}" || exit
		${GIT} pull >/dev/null 2>&1
	fi
done
