#!/bin/sh

# shellcheck source=/dev/null
. "$HOME/.config/common"

if [ ! -d "${MANDIR}" ]; then
	mkdir -p "${MANDIR}"
	exit 1
fi

readonly MANUAL=$(
	for manual in $(find "${MANDIR}" -type f | sed -e "s|${MANDIR}/||g"); do
		echo "${manual}"
	done | dmenu -i -p "open manual:"
)

readonly MANUALPATH="${MANDIR}/${MANUAL}"
if [ -z "${MANUAL}" ] || [ ! -f "${MANUALPATH}" ]; then
	exit 1
fi

${MANVIEW} "${MANUALPATH}" &
