#!/usr/bin/env bash
#--------------------- Variables.
declare -A streams
declare -A streamtype
#--------------------- Read each stream. 
while read -r stream url type; do
	streams[$stream]=$url
	streamtype[$stream]=$type
done < <(sed "/^#/d" "$HOME/.config/streams")
#--------------------- Select stream via dmenu.
stream=$(for i in "${!streams[@]}"; do echo "$i"; done | sort -us | dmenu -i -p "select stream:" "$@")
#--------------------- Check stream type then play via mpv.
case "${streamtype[${stream}]}" in
	video)
		mpv --background="$(grep -owE "#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})" "$HOME/.suckless/themes/theme.h" | sed -n 2p)" "${streams[$stream]}"
		;;
	music)
		st -e mpv "${streams[$stream]}"	
		;;
	*)
		exit 1
		;;
esac
#---------------------
