#!/usr/bin/env bash
#shellcheck disable=SC2015
declare -A streams
declare -A type

[[ "$#" -eq 2 ]] && {
	streams[key]=$2
	type[key]=$1
} || while read -r label url type; do
	[[ -z "$label" || -z "$url" || -z "$type" ]] && continue || {
		streams[$label]=$url
		type[$label]=${type,,}
	}
done < <(sed "/^#/d" "$HOME/.config/streams")

[[ "${#streams[@]}" -eq 0 ]] && exit 0 || {
	[[ -z "${type[key]}" ]] && label=$(for label in "${!streams[@]}"; do echo "$label"; done | sort -us | dmenu -i -p "open stream:") || label=key
	case "${type[${label}]}" in
		v|video)
			mpv --background="$(awk -F\" '/#([A-Fa-f0-9]).*background$/{if(length($2)>=4)print$2}' "$HOME/.suckless/app/theme.h")" "${streams[$label]}" &>/dev/null &
			;;
		a|audio)
			st -e mpv --video=no "${streams[$label]}" &>/dev/null &
			;;
		*)
			exit 0
			;;
	esac
}
