#!/bin/sh

# shellcheck source=/dev/null
. "/usr/home/${USER}/.config/common"

readonly PREFIX=/usr/local
readonly DMENU=${PREFIX}/bin/dmenu

readonly FIND=/usr/bin/find
readonly MKDIR=/bin/mkdir
readonly SED=/usr/bin/sed

if [ ! -d "${MANDIR}" ]; then
	${MKDIR} -p "${MANDIR}"
	exit 1
fi

readonly MANUAL=$(
	for manual in $(${FIND} "${MANDIR}" -type f | ${SED} -e "s|${MANDIR}/||g"); do
		echo "${manual}"
	done | ${DMENU} -i -p "open manual:"
)

readonly MANUALPATH="${MANDIR}/${MANUAL}"
if [ -z "${MANUAL}" ] || [ ! -f "${MANUALPATH}" ]; then
	exit 1
fi

${MANVIEW} "${MANUALPATH}" &
