#!/usr/bin/env bash
#shellcheck disable=SC2155

notify_track() {
	local __ENDPOINT="https://api.spotify.com/v1/tracks"	
	local __USER="$LOCAL_USER"
	local __OAUTH="$TOKEN"
	local __TRACK="$TRACK_ID"
	local __DATA=$(curl -s -X "GET" "$__ENDPOINT"/"$__TRACK" -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer $__OAUTH")
	local __ICON_URL=$(echo "$__DATA" | jq -r .album.images[2].url)
	
	local __ERROR=$(echo "$__DATA" | jq -r .error) 
	[[ ! "$__ERROR" == "null" ]] && {
		local __STATUS=$(echo "$__ERROR" | jq -r .status)
		local __MESSAGE=$(echo "$__ERROR" | jq -r .message)
		su "$__USER" -c "notify-send -t 4500 \"[Spotify] Error.\" \"$__STATUS: $__MESSAGE.\""
		exit
	}

	export __ICON_TMP="/tmp/spotifyd-icon"
	fetch -qo - "$__ICON_URL" > "$__ICON_TMP"
	chown "$__USER":"$__USER" "$__ICON_TMP"
		
	export __NAME=$(echo "$__DATA" | jq -r .name)
	export __ARTIST=$(echo "$__DATA" | jq -r .artists[0].name)

	su "$__USER" -c "notify-send -t 4500 -i \"$__ICON_TMP\" \"[Spotify] $*\" \"<b>$__NAME</b>, by <i>$__ARTIST</i>.\""
}

case "$PLAYER_EVENT" in
	start|change)
		notify_track "Now playing"
		;;
	*)
		exit
	;;
esac
