#!/usr/bin/env sh

RED=$(tput AF 1)
WHITE=$(tput AF 7)
BOLD=$(tput md)
DEFAULT=$(tput me)

OS=$(uname -s)
KERNEL=$(uname -iK)
RELEASE=$(uname -r | sed s/[0-9a-z.-]//g)
PACKAGES=$(pkg info | wc -l | tr -d ' ')
WM=$(tail -n1 "${HOME}"/.xinitrc 2>/dev/null | awk '{print $2}' | tr "[:lower:]" "[:upper:]") 

cat <<EOF

${WHITE}${BOLD} /\ _____ /\ ${DEFAULT}
${WHITE}${BOLD} \_)     (_/        ${RED}____________________________
${RED} /         \        ${BOLD}${RED}OS		${WHITE}${OS}, ${RELEASE}
${RED}|           |       ${BOLD}${RED}KERNEL	${WHITE}${KERNEL}
${RED}|           |       ${BOLD}${RED}PACKAGES	${WHITE}${PACKAGES}
${RED} \         /        ${BOLD}${RED}WM		${WHITE}${WM:-NONE}
${RED}  --_____--         ${WHITE}----------------------------

EOF
