#!/usr/bin/env bash

results=$(ls -l $HOME/.suckless/themes/*.conf | wc -l | tr -d ' ')
awk -F ":" \
	'BEGIN {
		lines = sprintf("%75s", "")
		gsub(/ /, "-", lines)
		print lines
		print "theme\t\t accent\t\t background\t foreground\t border"	
		print lines
	}
		
	{
		print FILENAME,"\t",$1,"\t",$2,"\t",$3,"\t",$4
	}

	END {
		print lines
	}' $HOME/.suckless/themes/*.conf | sed -e "s/\/home\/$USER\/.suckless\/themes\///g" -e "s/.conf//g" 
echo "$results theme(s) found: type sys-theme-apply [theme] OR sysa [theme] to install"
echo "---------------------------------------------------------------------------"
