#!/usr/bin/env bash
#--------------------- Read input.
set -- "${1:-$(</dev/stdin)}" "${@:2}"
#--------------------- Variables.
sucklessdir=$HOME/.suckless
scriptdir=$HOME/.scripts
themeconf=$sucklessdir/themes/$1.conf
#--------------------- Check theme exists.
[[ ! -f "$themeconf" ]] && exit 1
#--------------------- Source theme.
source "$themeconf"
#--------------------- General appearance.
accent=${accent:-#1177AA}
background=${background:-#000000}
foreground=${foreground:-#FFFFFF}
font=${font:-Apercu Mono Pro:pixelsize=13:antialias=true:autohint=true}
#--------------------- DWM.
borderactive=${dwm_border_active:-#6592A8}
borderinactive=${dwm_border_inactive:-#405D6B}
borderpx=${dwm_border_px:-1}
showbar=${dwm_showbar:-1}
topbar=${dwm_topbar:-1}
horizpadpx=${dwm_horizpadpx:-1}
vertpadpx=${dwm_vertpadpx:-15}
tagind=${dwm_tagind:-2}
#--------------------- ST.
paddingpx=${st_padding_px:-15}
defaultcolors=(\
	"#101010"
  	"#FF6B57"
   	"#B8D68C"
  	"#E1AA5D"
 	"#7DC1CF"
   	"#9B64FB"
   	"#6D878D"
  	"#DDDDDD"
   	"#404040"
   	"#FF6B57"
   	"#A0CF5D"
   	"#F39D21"
  	"#4E9FB1"
  	"#8542FF"
   	"#42717B"
	"#DDDDDD"
)
colors=(${st_colors[@]:-${defaultcolors[@]}})
#--------------------- Generate C headerfile.
cat > "$sucklessdir/themes/theme.h" <<EOF
typedef struct {
	char font[255];
	char accent[8];
	char background[8];
	char foreground[8];
	struct {
		char border_active[8];
		char border_inactive[8];
	} dwm;
	struct {
		char black[8];
		char red[8];
		char green[8];
		char yellow[8];
		char blue[8];
		char magenta[8];
		char cyan[8];
		char white[8];
		char bright_black[8];
		char bright_red[8];
		char bright_green[8];
		char bright_yellow[8];
		char bright_blue[8];
		char bright_magenta[8];
		char bright_cyan[8];
		char bright_white[8];
	} st;
} Theme;

/* theme: $1 */
static const Theme theme = {
	/* main appearance */
	"${font}",
	"${accent}", /* accent     */
	"${background}", /* background */
	"${foreground}", /* foreground */
	{ 
		/* dwm */
		"${borderactive}",	/* border active   */
		"${borderinactive}"	/* border inactive */
	},
	{
		/* st */
		/* normal color       */
		"${colors[0]}", /* black   */
		"${colors[1]}", /* red     */
		"${colors[2]}", /* green   */
		"${colors[3]}", /* yellow  */
		"${colors[4]}", /* blue    */
		"${colors[5]}", /* magenta */
		"${colors[6]}", /* cyan    */
		"${colors[7]}", /* white   */
	 	/* bright color       */
		"${colors[8]}", /* black   */
		"${colors[9]}", /* red     */
		"${colors[10]}", /* green   */
		"${colors[11]}", /* yellow  */
		"${colors[12]}", /* blue    */
		"${colors[13]}", /* magenta */
		"${colors[14]}", /* cyan    */
		"${colors[15]}"  /* white   */
	}
};
/* defines */
#define _borderpx ${borderpx} 
#define _paddingpx ${paddingpx}
#define _showbar ${showbar}
#define _topbar ${topbar}
#define _horizpadbar ${horizpadpx}
#define _vertpadbar ${vertpadpx}
#define _tagind ${tagind}
EOF
#--------------------- Recompile suckless utilities.
doas make CC="ccache cc" clean install -C "$sucklessdir/dwm" &> /dev/null
doas make CC="ccache cc" clean install -C "$sucklessdir/dmenu" &> /dev/null
doas make CC="ccache cc" clean install -C "$sucklessdir/st" &> /dev/null
#--------------------- Update arbitrary configs.
source "$scriptdir/.themer/wallpaper"
source "$scriptdir/.themer/zathura"
source "$scriptdir/.themer/neovim"
source "$scriptdir/.themer/dunst"
#--------------------- Restart dwm.
xdotool key 'Super+q'
#---------------------
notify-send "<b>SYSTEM THEME UPDATED</b>" "Theme changed to '<i>$1</i>'."
#---------------------
